version: "3"

services:
  web: 
    image: proyector:v7
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_ENV: dev
    volumes:
      - ./:/var/www/
    ports:
      - 3000:80  
    networks:
      - proyector 
networks:
  proyector:       
